<?php

namespace Container9hIx0JI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeterReaderSuspiciousFinderService extends App_src_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Electricity\MeterReader\Application\FindSuspiciousReading\MeterReaderSuspiciousFinder' shared autowired service.
     *
     * @return \App\Electricity\MeterReader\Application\FindSuspiciousReading\MeterReaderSuspiciousFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Electricity/MeterReader/Application/FindSuspiciousReading/MeterReaderSuspiciousFinder.php';
        include_once \dirname(__DIR__, 4).'/src/Electricity/MeterReader/Domain/MeterReaderRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Electricity/MeterReader/Infrastructure/Parser/MeterReaderParser.php';

        return $container->privates['App\\Electricity\\MeterReader\\Application\\FindSuspiciousReading\\MeterReaderSuspiciousFinder'] = new \App\Electricity\MeterReader\Application\FindSuspiciousReading\MeterReaderSuspiciousFinder(($container->privates['App\\Electricity\\MeterReader\\Infrastructure\\Parser\\MeterReaderParser'] ?? ($container->privates['App\\Electricity\\MeterReader\\Infrastructure\\Parser\\MeterReaderParser'] = new \App\Electricity\MeterReader\Infrastructure\Parser\MeterReaderParser())));
    }
}
