<?php

namespace ContainerMwgAOxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_WaW8NJ3Service extends App_src_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.waW8NJ3' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Electricity/MeterReader/Application/FindSuspiciousReading/MeterFindSuspiciousReadHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Electricity/MeterReader/Application/FindSuspiciousReading/MeterReaderSuspiciousFinder.php';
        include_once \dirname(__DIR__, 4).'/src/Electricity/MeterReader/Domain/MeterReaderRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Electricity/MeterReader/Infrastructure/Parser/MeterReaderParser.php';

        return $container->privates['.messenger.handler_descriptor.waW8NJ3'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Electricity\MeterReader\Application\FindSuspiciousReading\MeterFindSuspiciousReadHandler(new \App\Electricity\MeterReader\Application\FindSuspiciousReading\MeterReaderSuspiciousFinder(new \App\Electricity\MeterReader\Infrastructure\Parser\MeterReaderParser())), []);
    }
}
