<?php

namespace ContainerMwgAOxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeterReaderCommandService extends App_src_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Electricity\MeterReader\EntryPoint\UI\Command\MeterReaderCommand' shared autowired service.
     *
     * @return \App\Electricity\MeterReader\EntryPoint\UI\Command\MeterReaderCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Electricity/MeterReader/EntryPoint/UI/Command/MeterReaderCommand.php';

        return $container->services['console.command.public_alias.App\\Electricity\\MeterReader\\EntryPoint\\UI\\Command\\MeterReaderCommand'] = new \App\Electricity\MeterReader\EntryPoint\UI\Command\MeterReaderCommand(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));
    }
}
