<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9hIx0JI\App_src_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9hIx0JI/App_src_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container9hIx0JI.legacy');

    return;
}

if (!\class_exists(App_src_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container9hIx0JI\App_src_KernelTestDebugContainer::class, App_src_KernelTestDebugContainer::class, false);
}

return new \Container9hIx0JI\App_src_KernelTestDebugContainer([
    'container.build_hash' => '9hIx0JI',
    'container.build_id' => '24a60caf',
    'container.build_time' => 1604149916,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9hIx0JI');
