<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMwgAOxi\App_src_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMwgAOxi/App_src_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMwgAOxi.legacy');

    return;
}

if (!\class_exists(App_src_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMwgAOxi\App_src_KernelDevDebugContainer::class, App_src_KernelDevDebugContainer::class, false);
}

return new \ContainerMwgAOxi\App_src_KernelDevDebugContainer([
    'container.build_hash' => 'MwgAOxi',
    'container.build_id' => '44d90871',
    'container.build_time' => 1604147536,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMwgAOxi');
