<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXsZKO0L\App_src_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXsZKO0L/App_src_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXsZKO0L.legacy');

    return;
}

if (!\class_exists(App_src_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXsZKO0L\App_src_KernelDevDebugContainer::class, App_src_KernelDevDebugContainer::class, false);
}

return new \ContainerXsZKO0L\App_src_KernelDevDebugContainer([
    'container.build_hash' => 'XsZKO0L',
    'container.build_id' => '01801dac',
    'container.build_time' => 1604149844,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXsZKO0L');
