<?php

namespace ContainerX2Cr00a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeterFindSuspiciousReadHandlerService extends App_src_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Electricity\MeterReader\Application\FindSuspiciousReading\MeterFindSuspiciousReadHandler' shared autowired service.
     *
     * @return \App\Electricity\MeterReader\Application\FindSuspiciousReading\MeterFindSuspiciousReadHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Electricity/MeterReader/Application/FindSuspiciousReading/MeterFindSuspiciousReadHandler.php';

        return $container->privates['App\\Electricity\\MeterReader\\Application\\FindSuspiciousReading\\MeterFindSuspiciousReadHandler'] = new \App\Electricity\MeterReader\Application\FindSuspiciousReading\MeterFindSuspiciousReadHandler(($container->privates['App\\Electricity\\MeterReader\\Application\\FindSuspiciousReading\\MeterReaderSuspiciousFinder'] ?? $container->load('getMeterReaderSuspiciousFinderService')));
    }
}
